/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicando;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class JFProducto extends javax.swing.JFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form JFProducto
     */
    public JFProducto() {
        initComponents();
        cargarProducto();
        this.setLocationRelativeTo(null);
    }
    
    void cargarProducto(){
        
        ArrayList<Object> nombreColumna; 
        nombreColumna = new ArrayList<Object>();
        
        nombreColumna.add("Código Producto");
        nombreColumna.add("Descripción");
        nombreColumna.add("Precio Unitario");
        
        nombreColumna.forEach((columna) -> {
            modelo.addColumn(columna);
        });
        
        this.jTblProductos.setModel(modelo);
        
        ArrayList<Object> productos = new ArrayList<Object>();
        Object[] productos1 = new Object[]{"1234", "Samsung Galaxy S10+", "25000.00"};
        Object[] productos2 = new Object[]{"1235", "Xiaomi MI9", "12000.00"};
        Object[] productos3 = new Object[]{"1236", "Samsung Note 10 pro", "35000.00"};
        Object[] productos4 = new Object[]{"1237", "Sony Xperia", "15000.00"};
        Object[] productos5 = new Object[]{"1238", "Huawei Y6", "9500.00"};
        Object[] productos6 = new Object[]{"1239", "Samsung S7", "4500.00"};
        Object[] productos7 = new Object[]{"1240", "Xiaomi Note 9", "6500.00"};
        Object[] productos8 = new Object[]{"1241", "Huawei P40 Pro", "19500.00"};
        Object[] productos9 = new Object[]{"1242", "Iphone 8 plus", "8500.00"};
        Object[] productos10 = new Object[]{"1243", "Iphone X", "13500.00"};
        
        productos.add(productos1);
        productos.add(productos2);
        productos.add(productos3);
        productos.add(productos4);
        productos.add(productos5);
        productos.add(productos6);
        productos.add(productos7);
        productos.add(productos8);
        productos.add(productos9);
        productos.add(productos10);
        
        
        
        productos.forEach((Object productoDato) -> {
            modelo.addRow((Object[]) productoDato);
        });
        
        this.jTblProductos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProductos = new javax.swing.JTable();
        jBtnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Listado de productos");

        jScrollPane1.setViewportView(jTblProductos);

        jBtnSeleccionar.setText("Seleccionar");
        jBtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSeleccionar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSeleccionar)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeleccionarActionPerformed
        // TODO add your handling code here:
        
        filaSeleccionada();
    }//GEN-LAST:event_jBtnSeleccionarActionPerformed

    
    private void filaSeleccionada(){
        
        String codProducto, descripcion, precioUnitario;
        
        if(this.jTblProductos.getSelectedRow() != -1){
            int filaSeleccionada;
            
            filaSeleccionada = this.jTblProductos.getSelectedRow();
            
            codProducto = this.jTblProductos.getValueAt(filaSeleccionada, 0).toString();
            descripcion = this.jTblProductos.getValueAt(filaSeleccionada, 1).toString();
            precioUnitario = this.jTblProductos.getValueAt(filaSeleccionada, 2).toString();

            JFFactura.jTFCodProducto.setText(codProducto);
            JFFactura.jTFDescripcionProducto.setText(descripcion);
            JFFactura.jTFPreUnit.setText(precioUnitario);
            
            dispose();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblProductos;
    // End of variables declaration//GEN-END:variables
}
